### ISSUE TITLE
Print Values of Array

### ISSUE THREAD

**Issue by saumy007** [heysaiyad/DSA#130]
to print values of array

**Comment by sahil5910** [comment]
Hey i Can do this task, can you assign it to me

**Comment by Rohantiwari10** [comment]
Can you assign this to me?

**Comment by Himanshu66109** [comment]
@saumy007 Please assign me this Problem.

**Comment by GhostRider987** [comment]
Can you please assign me with this issue. I will add a great solution for this.

**Comment by Agnihotrimansi** [comment]
hello sir please assign me this issue.
