### ISSUE TITLE
Floyd's cycle detection

### ISSUE THREAD

**Issue by sowmya061** [heysaiyad/DSA#15]
I would like to work on this issue in c++ . Kindly assign me this @heysaiyad

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by PooniaPankaj** [comment]
Hello sir , I am well versed with c++ . I already worked on that problem please assign it to me .

**Comment by Shreekar11** [comment]
Hi there !!
I have great & deep knowledge about LinkedList and the Floyd's cycle detection. It would be great to contribute and help towards the problem statement.
Please Assign me the following task.

Cheers !!

**Comment by Satyam9119** [comment]
Hello @heysaiyad , I have previously worked on this issue. please assign it to me .

**Comment by srusti610** [comment]
Hello sir 
I can contribute to this issue kindly assign it to me.
