### ISSUE TITLE
Kadane's Algorithm in C++

### ISSUE THREAD

**Issue by heysaiyad** [heysaiyad/DSA#2]

**Comment by Aarsh30** [comment]
heyy can you assign it me i have done this

**Comment by sdehury34** [comment]
Hi please assign this task to me! I can do this.

**Comment by Tejoooo** [comment]
can u assign me this issue

**Comment by kadamprashant1** [comment]
Hope you are well, I can solve this issue very sincerely with good, beatified code.

**Comment by Modernbeast02** [comment]
Hey @heysaiyad Can you assign this to me?

**Comment by adityasankar5** [comment]
Hey can i please have this assigned to me. I will be contributing this code in python

**Comment by Satyam9119** [comment]
Hey, can you please assign this task to me. I can do this.
