### ISSUE TITLE
I would like to add DFS and BFS algorithms in Graphs

### ISSUE THREAD

**Issue by Niyati3031** [heysaiyad/DSA#20]
Can you please assign this to me for hacktoberfest 2023

**Comment by cu-sanjay** [comment]
Would it be possible to assign me the task of adding BFS and DFS algorithms ? I'd be happy to contribute to this project by implementing these algorithms.

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by Modernbeast02** [comment]
Hey, Can you assign me this task?

**Comment by Sweta-Raj31** [comment]
Hey Saiyad Can you please assign this to me.
