### ISSUE TITLE
Want to Add Graph Problems.

### ISSUE THREAD

**Issue by knockcat** [heysaiyad/DSA#233]
I want to add famous graph algorithms on the graph section please assign me with this task.

**Comment by knockcat** [comment]
I have made a pull request with Graph problem and added 5 problems, Plese review them.

**Comment by Samarthku** [comment]
Heyy! @heysaiyad 
i want to add oops structure this program this program please assign me this issue.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
