### ISSUE TITLE
I would like to add Dijkstra's algorithm

### ISSUE THREAD

**Issue by CDT-PRATEEK** [heysaiyad/DSA#236]
Can you label it as hacktoberfest-accepted

**Comment by Samarthku** [comment]
Hey there, @CDT-PRATEEK 
you can assign me this issue
i am solve this issue

**Comment by balkishan69** [comment]
Hey @heysaiyad can u please assign me this issue

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
