### ISSUE TITLE
Rat In a Maze

### ISSUE THREAD

**Issue by sowmya061** [heysaiyad/DSA#24]
I would like to add this code in c++ . Kindly assign me this

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by sahil5910** [comment]
Hey, i have made the PR kindly merge it. 
Thank you

**Comment by Sweta-Raj31** [comment]
Hey Saiyad Can you please assign this to me.
