### ISSUE TITLE
Want to add inorder,preorder,postorder traversal under trees.

### ISSUE THREAD

**Issue by Naman73598** [heysaiyad/DSA#249]
hey @heysaiyad , please assign me the this issue.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by slaughterhectic** [comment]
Hello @Naman73598 can you please assign me this I have more than 100+ dsa code it will be nothing but very easy for me

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
