### ISSUE TITLE
I want to add the solution of the 4 Sum problem

### ISSUE THREAD

**Issue by Sayak-Bhunia** [heysaiyad/DSA#253]
Please label this hacktoberfest accepted

**Comment by Sayak-Bhunia** [comment]
hey @heysaiyad please label and assign me this issue.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
