### ISSUE TITLE
Want to add Knapsack Problem and the longest common subsequence problem under Dynamic Programming

### ISSUE THREAD

**Issue by TANYA03GUPTA** [heysaiyad/DSA#257]

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by TANYA03GUPTA** [comment]
@heysaiyad Kindly assign this issue to me as i have alreadyadded these and submitted a pr as well

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
