### ISSUE TITLE
Want to add Linear search algorithm 

### ISSUE THREAD

**Issue by DibyashaktiMoharana** [heysaiyad/DSA#270]
Want to add the code to the searching directory

**Comment by DibyashaktiMoharana** [comment]
Please assign hacktoberfest label to this

**Comment by dev1abhi** [comment]
I want to work on this . please assign me @heysaiyad

**Comment by DibyashaktiMoharana** [comment]
Fixed the issue. @heysaiyad #270

**Comment by dev1abhi** [comment]
> Fixed the issue. @heysaiyad #270

Ok

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by MazeJack** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
