### ISSUE TITLE
In Arrays Fascinationg Number 

### ISSUE THREAD

**Issue by saumy007** [heysaiyad/DSA#284]
In Arrays Fascinationg Number : Fascinating Number: When a number( 3 digits or more ) is multiplied by 2 and 3, and when both these products are concatenated with the original number, then it results in all digits from 1 to 9 present exactly once. There could be any number of zeros and are ignored.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by rehan700** [comment]
Bhai AW,

Assign this to me under HACKTOBERFEST'2023.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
