### ISSUE TITLE
Boundary Traversal of Matrix

### ISSUE THREAD

**Issue by Ash0807** [heysaiyad/DSA#285]
**Describe the Issue**
We have given a matrix of dimensions n x m. The task is to perform boundary traversal on the matrix in a clockwise manner.

**Sample Input:**
n = 4, m = 4
matrix[ ][ ] = {{1, 2, 3, 4},
         {5, 6, 7, 8},
         {9, 10, 11, 12},
         {13, 14, 15,16}}

**Sample Output:** 1 2 3 4 8 12 16 15 14 13 9 5

**Additional context (optional )**
@heysaiyad can you please assign this issue to me @Ash0807 under Hacktoberfest label ?

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
