### ISSUE TITLE
Transpose of Matrix

### ISSUE THREAD

**Issue by Ash0807** [heysaiyad/DSA#286]
**Describe the Issue**
We have to find out the transpose of a square matrix of size N*N by changing rows to columns and columns to rows.

**Sample Input:**
N = 4
mat[][] = {{1, 1, 1, 1},
           {2, 2, 2, 2}
           {3, 3, 3, 3}
           {4, 4, 4, 4}}

**Sample Output:** 
{{1, 2, 3, 4},  
 {1, 2, 3, 4}  
 {1, 2, 3, 4}
 {1, 2, 3, 4}} 

Additional context (optional )
@heysaiyad can you please assign this issue to me @Ash0807 under Hacktoberfest label ?

**Comment by Sayan-Shaw11** [comment]
Please assign this to me.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by rehan700** [comment]
Hey bro AW,

I want contribute to this issue, please assign it to me under HACKTOBERFEST'2023.

**Comment by iamakashrout** [comment]
Please assign this to me
