### ISSUE TITLE
Kahn’s Algorithm

### ISSUE THREAD

**Issue by muskandn** [heysaiyad/DSA#292]
Given a [Directed Acyclic Graph (DAG)](https://takeuforward.org/graph/introduction-to-graph/) with V vertices and E edges, Find any Topological Sorting of that Graph. In topological sorting, node u will always appear before node v if there is a directed edge from node u towards node v(u -> v).

I want to code this very important algorithm in C++.
@heysaiyad  Please assign this issue to me.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by iamakashrout** [comment]
Please assign this to me. I'm interested tin contributing

**Comment by Krismandanka** [comment]
Hello, I am skilled in C++ I have solved 390+ questions on leetcode can you assign me this?

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
