### ISSUE TITLE
Matrix multiplication

### ISSUE THREAD

**Issue by harshalijain14** [heysaiyad/DSA#300]
I would like to add a program of matrix multiplication using C++ in your matrix folder of the repository.

**Comment by iamakashrout** [comment]
please assign this issue to me

**Comment by Sarthakgarg-04** [comment]
Please assign this issue to me , i would like to contribute the program for matrix multiplication using JAVA.

**Comment by Krismandanka** [comment]
Hello, I am skilled in C++ I have solved 390+ questions on leetcode can you assign me this?

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
