### ISSUE TITLE
Interval map DS

### ISSUE THREAD

**Issue by acf-patrick** [heysaiyad/DSA#315]
# Interval map
*Interval map* is a data structure that associates keys of type __K__ with values of type __V__. It is designed to be used efficiently in situations where intervals of consecutive keys are associated with the same value.
The implementation can be done on top of __std::map__ Let's assume that items are kept in a _std::map_ instance called __m_map__

Each key-value-pair _(k, v)_ in __m_map__ means that the value __v__ is associated with all keys from __k__ (including) to the next key (excluding) in _m_map_. Doing so, we need to add a new variable *m_valBegin* to hold the value that is associated with all keys less than the first key in __m_map__.

> To allow various types as key and value, we could use templates.

Let __M__ be an instance of our new class ```interval_map<int, char>``` where 
```C++
M.m_valBegin == 'A',
M.m_map == { ( 1, 'B' ), ( 3, 'A' ) }
```

Then M represents the mapping
```
...
-2 -> 'A'
-1 -> 'A'
 0 -> 'A'
 1 -> 'B'
 2 -> 'B'
 3 -> 'A'
 4 -> 'A'
 5 -> 'A'
...
```

## Optimisation
The representation in the ```std::map<K, V> m_map``` must be cannonical, that is, consecutive map entries must not contain the same value : ```..., (3, 'A'), (5, 'A'), ...``` should not be allowed. Likewise, the first entry in __m_map__ must not contain the same value as __m_valBegin__. 

> Initially, the whole range of __K__ is associated with a given initial value.

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
