### ISSUE TITLE
Kruskal’s Algorithm

### ISSUE THREAD

**Issue by muskandn** [heysaiyad/DSA#332]
Kruskal’s Algorithm – Minimum Spanning Tree

Problem Statement: Given a weighted, undirected, and connected graph of V vertices and E edges. The task is to find the sum of weights of the edges of the Minimum Spanning Tree.

**Comment by muskandn** [comment]
I want to code this problem in C++
@heysaiyad please assign this issue to me

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
