### ISSUE TITLE
Lowest Common Ancestor for two given Nodes

### ISSUE THREAD

**Issue by muskandn** [heysaiyad/DSA#335]
Problem Statement: Given a binary tree, Find the Lowest Common Ancestor for two given Nodes (x,y).

Lowest Common Ancestor(LCA): The lowest common ancestor is defined between two nodes x and y as the lowest node in T that has both x and y as descendants (where we allow a node to be a descendant of itself.

**Comment by muskandn** [comment]
This is a frequently asked in the interviews.
I want to work on this issue
@heysaiyad please assign this issue to me under Hacktoberfest2023

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.

**Comment by Anuj0918** [comment]
This is a famous interview question  asked in the interviews.
I want to work on this issue
@heysaiyad please assign this issue to me under Hacktoberfest2023
