### ISSUE TITLE
Strassen’s Matrix Multiplication Algorithm in CPP [Hacktoberfest'23]

### ISSUE THREAD

**Issue by sp9324** [heysaiyad/DSA#348]
**Description**:
I suggest adding the implementation of Strassen’s Matrix Multiplication Algorithm to the 'Matrix' folder in the repository. Strassen’s Matrix Multiplication Algorithm is a fast algorithm for multiplying matrices. It is even faster than the Karatsuba algorithm for large matrices, but it is also more complex.

**Language**: C++
Algorithm: Strassen’s Matrix Multiplication Algorithm

**Features**:
Asymptotic complexity: The Strassen algorithm has an asymptotic time complexity of O(n^log2(7)), which is faster than the standard matrix multiplication algorithm, which has an asymptotic time complexity of O(n^3).
Recursiveness: The Strassen algorithm is a recursive algorithm, which means that it calls itself to solve smaller subproblems. This can be inefficient for small matrices, but it is very efficient for large matrices.
Parallelization: The Strassen algorithm can be parallelized, which means that it can be run on multiple processors at the same time. This can further improve its performance for very large matrices.

@heysaiyad Kindly assign this issue to me under Hacktoberfest'23. Thanks!

**Comment by Ashima2003** [comment]
Heyy I want to work on this issue. Please assign it to me.
