### ISSUE TITLE
Bubble Sort in CPP 

### ISSUE THREAD

**Issue by Vyshnavi21504** [heysaiyad/DSA#36]
Bubble Sort is the simplest [sorting algorithm] that works by repeatedly swapping the adjacent elements if they are in the wrong order

**Comment by SayaliMarathe-13** [comment]
Hello,
I'm relatively new to open source and GitHub. I'm eager to learn and improve my skills, and I believe working on this issue will be a valuable experience for me. could you please assign it to me

**Comment by prabhoot** [comment]
#49 This have the bubble sorting code you can close this issue

**Comment by RishitaGangwal** [comment]
Hey, I would like to work on this issue. Kindly assign me this issue.

**Comment by Vyshnavi21504** [comment]
@heysaiyad I was the one to make this issue. pls assign me this issue

**Comment by AbhineshJha** [comment]
I am interested in this issue and i wanna give it a try ...

**Comment by SayaliMarathe-13** [comment]
Please accept my pr under hacktoberfest 2023
