### ISSUE TITLE
Stack using Linked List

### ISSUE THREAD

**Issue by heysaiyad** [heysaiyad/DSA#4]

**Comment by Aarsh30** [comment]
can you assign it me

**Comment by SRUJANA2199** [comment]
hi, i would like to work on this can you assign this to me under hacktoberfest 23 ?

**Comment by kadamprashant1** [comment]
hey, hope you are well, can you assign me this issue?

**Comment by RahaneSayali** [comment]
can you assign this issue to me

**Comment by SRUJANA2199** [comment]
well i did a pr,do check it out
