### ISSUE TITLE
Add topic wise Problems

### ISSUE THREAD

**Issue by heysaiyad** [heysaiyad/DSA#5]

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by nancy-singh10** [comment]
Scrapping upcoming hackathons and events.
@heysaiyad I want to work on this issue under hacktober fest.

**Comment by Kritikajain6104** [comment]
i want to work on this issue

**Comment by RahaneSayali** [comment]
assign this to me

**Comment by Devasahoo123** [comment]
plz assign me i am good programmer and  i do cp

**Comment by Satyam9119** [comment]
I can contribute in this issue. Please assign it to me sir @heysaiyad

**Comment by kittoteja** [comment]
Please assign it to me
