### ISSUE TITLE
Add Sorting Problems 

### ISSUE THREAD

**Issue by PratyushSinha15** [heysaiyad/DSA#6]

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by kadamprashant1** [comment]
Kindly assign this issue to me.

**Comment by RahaneSayali** [comment]
assign this to me

**Comment by www-cool** [comment]
Hi I want to contribute on this module

**Comment by priyanshuv-raw** [comment]
Hi sir, I want to contribute to this repo with all my library of Sorting Problems, which are relatively larger.
