### ISSUE TITLE
Dynamic programming problem 

### ISSUE THREAD

**Issue by nancy-singh10** [heysaiyad/DSA#9]
I want to add dp problem kindly assign this issue under Hacktober 23 @heysaiyad

**Comment by Tejoooo** [comment]
can u assign me this issue

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by kadamprashant1** [comment]
Hello, I am good in Python programming language can you assign this issue to me ?
I will resolve the issue sincerely.
